In [1]:
import pandas as pd

In [5]:
user_info = pd.read_csv('dataset/ml-1m/ml-1m.user', sep='\t')

In [7]:
metric_info = pd.read_csv('output/ml-1m/LightGCN/ndcg@10.csv')

In [8]:
metric_info

      ndcg@10
0      0.1312
1      0.0000
2      0.1208
3      0.6509
4      0.2201
...       ...
6035   0.3590
6036   0.0851
6037   0.0000
6038   0.2064
6039   0.1795

[6040 rows x 1 columns]

In [9]:
user_info['ndcg@10'] = metric_info.values

In [10]:
user_info

,user_id:token,age:token,gender:token,occupation:token,zip_code:token,ndcg@10
0,1,1,F,10,48067,0.1312
1,2,56,M,16,70072,0.0000
2,3,25,M,15,55117,0.1208
3,4,45,M,7,02460,0.6509
4,5,25,M,20,55455,0.2201
...,...,...,...,...,...,...
6035,6036,25,F,15,32603,0.3590
6036,6037,45,F,1,76006,0.0851
6037,6038,56,F,1,14706,0.0000
6038,6039,45,F,0,01060,0.2064
6039,6040,25,M,6,11106,0.1795

In [12]:
user_info.groupby('age:token')['ndcg@10'].mean()

age:token
1     0.246405
18    0.279030
25    0.295642
35    0.268526
45    0.230937
50    0.233655
56    0.210339
Name: ndcg@10, dtype: float64

In [13]:
user_info.groupby('age:token')['ndcg@10'].size()

age:token
1      222
18    1103
25    2096
35    1193
45     550
50     496
56     380
Name: ndcg@10, dtype: int64

In [15]:
user_info['ndcg@10'].mean()

0.26909380794701987